"""백본 모델 카탈로그.

프론트엔드 src/constants/baselineModels.ts 의 MODELS / BACKBONE_MODEL_MAP 을 그대로 반영합니다.
프론트엔드가 로컬 폴백으로 사용하는 목록과 동일하게 유지해 라운드트립을 보장합니다.
"""
from __future__ import annotations

from .schemas import BackboneModel, DataType, TaskType

MODELS: dict[str, BackboneModel] = {
    # ── 이미지 분류
    "convnext_v2_b": BackboneModel(
        id="convnext_v2_b",
        name="ConvNeXt-B (CLIP)",
        githubUrl="https://github.com/facebookresearch/ConvNeXt",
        paperUrl="https://arxiv.org/abs/2301.00808",
        downloadUrl="https://huggingface.co/timm/convnext_base.clip_laion2b_augreg_ft_in1k",
        framework="pytorch",
        description="CLIP LAION-2B 사전학습 후 ImageNet-1k 파인튜닝. 전이학습 성능 우수. timm 자동 다운로드.",
        installPackages=["timm", "torch", "torchvision"],
    ),
    "efficientnet_v2_m": BackboneModel(
        id="efficientnet_v2_m",
        name="EfficientNetV2-M",
        githubUrl="https://github.com/google/automl/tree/master/efficientnetv2",
        paperUrl="https://arxiv.org/abs/2104.00298",
        downloadUrl="https://huggingface.co/timm/tf_efficientnetv2_m.in21k_ft_in1k",
        framework="pytorch",
        description="속도-정확도 균형. 소규모 데이터 파인튜닝에 강세. timm으로 로드 가능.",
        installPackages=["timm", "torch", "torchvision"],
    ),
    "swin_v2_b": BackboneModel(
        id="swin_v2_b",
        name="Swin Transformer V2-B",
        githubUrl="https://github.com/microsoft/Swin-Transformer",
        paperUrl="https://arxiv.org/abs/2111.09883",
        downloadUrl="/api/models/swin_v2_b",
        localFile=True,
        framework="pytorch",
        description="고해상도 입력·세밀한 분류에 강함. 대규모 사전학습 활용.",
        installPackages=["timm", "torch", "torchvision"],
    ),
    # ── 이미지 세그멘테이션
    "sam2": BackboneModel(
        id="sam2",
        name="SAM 2 (Hiera-Large)",
        githubUrl="https://github.com/facebookresearch/sam2",
        paperUrl="https://arxiv.org/abs/2408.00714",
        downloadUrl="https://dl.fbaipublicfiles.com/segment_anything_2/092824/sam2.1_hiera_large.pt",
        framework="pytorch",
        description="2024 파운데이션 모델. LoRA 파인튜닝 지원. 산업 검사·의료 영상에 탁월.",
        installPackages=["sam2", "torch", "torchvision"],
    ),
    "segformer_b5": BackboneModel(
        id="segformer_b5",
        name="SegFormer-B5",
        githubUrl="https://github.com/NVlabs/SegFormer",
        paperUrl="https://arxiv.org/abs/2105.15203",
        downloadUrl="https://huggingface.co/nvidia/segformer-b5-finetuned-ade-640-640/resolve/main/pytorch_model.bin",
        framework="pytorch",
        description="경량 semantic segmentation. 텍스처 기반 소재 검사에 적합.",
        installPackages=["transformers", "torch", "torchvision"],
    ),
    "mask2former": BackboneModel(
        id="mask2former",
        name="Mask2Former",
        githubUrl="https://github.com/facebookresearch/Mask2Former",
        paperUrl="https://arxiv.org/abs/2112.01527",
        downloadUrl="https://huggingface.co/facebook/mask2former-swin-large-coco-instance/resolve/main/pytorch_model.bin",
        framework="pytorch",
        description="Instance/Panoptic segmentation SOTA. 다중 인스턴스 정밀도 최고.",
        installPackages=["transformers", "torch", "torchvision"],
    ),
    # ── 객체 탐지
    "yolo26n": BackboneModel(
        id="yolo26n",
        name="YOLO26n",
        githubUrl="https://github.com/ultralytics/ultralytics",
        paperUrl="https://arxiv.org/abs/2606.03748",
        downloadUrl="https://github.com/ultralytics/assets/releases/latest/download/yolo26n.pt",
        framework="pytorch",
        description="2026 최신 YOLO. NMS-free, 경량 모델. 19개 배포 포맷 지원.",
        installPackages=["ultralytics"],
    ),
    "rf_detr_l": BackboneModel(
        id="rf_detr_l",
        name="RF-DETR-L",
        githubUrl="https://github.com/roboflow/RF-DETR",
        paperUrl="https://arxiv.org/abs/2411.12914",
        downloadUrl="https://huggingface.co/roboflow/rf-detr-l/resolve/main/rf-detr-l.pt",
        framework="pytorch",
        description="ICLR 2026. DINOv2 백본. COCO SOTA(75.1 mAP). 파인튜닝 최적화 설계.",
        installPackages=["rfdetr"],
    ),
    "rt_detr_v2_l": BackboneModel(
        id="rt_detr_v2_l",
        name="RT-DETR v2-L",
        githubUrl="https://github.com/lyuwenyu/RT-DETR",
        paperUrl="https://arxiv.org/abs/2407.17140",
        downloadUrl="https://github.com/ultralytics/assets/releases/latest/download/rtdetr-l.pt",
        framework="pytorch",
        description="실시간 트랜스포머 검출기. 높은 정확도와 실시간 추론 지원.",
        installPackages=["ultralytics"],
    ),
    # ── 이미지 이상탐지
    "patchcore": BackboneModel(
        id="patchcore",
        name="PatchCore",
        githubUrl="https://github.com/openvinotoolkit/anomalib",
        paperUrl="https://arxiv.org/abs/2106.08265",
        downloadUrl="https://download.pytorch.org/models/wide_resnet50_2-95faca4d.pth",
        downloadNote="WideResNet-50-2 백본 가중치 (PyTorch 공식). anomalib 설치 시 자동 다운로드됩니다.",
        framework="pytorch",
        description="CVPR 2022. 메모리 뱅크 기반 비지도 이상탐지. anomalib 공식 지원. 추가 학습 없이 정상 샘플만으로 동작.",
        installPackages=["anomalib", "torch"],
    ),
    "efficient_ad": BackboneModel(
        id="efficient_ad",
        name="EfficientAD",
        githubUrl="https://github.com/openvinotoolkit/anomalib",
        paperUrl="https://arxiv.org/abs/2303.14535",
        downloadUrl="https://huggingface.co/timm/efficientnet_b4.ra2_in1k/resolve/main/model.safetensors",
        downloadNote="EfficientNet-B4 교사 모델 가중치. anomalib 설치 시 timm으로 자동 다운로드.",
        framework="pytorch",
        description="WACV 2024. PDN 구조. 엣지 배포 최적. 카메라-레이트 속도 inference. anomalib 공식 지원.",
        installPackages=["anomalib", "torch"],
    ),
    "winclip": BackboneModel(
        id="winclip",
        name="WinCLIP",
        githubUrl="https://github.com/caoyunkang/WinCLIP",
        paperUrl="https://arxiv.org/abs/2303.14814",
        downloadUrl="https://huggingface.co/laion/CLIP-ViT-L-14-laion2B-s32B-b82K/resolve/main/open_clip_pytorch_model.bin",
        framework="pytorch",
        description="CVPR 2023. OpenCLIP 기반 zero/few-shot 이상탐지. 정상 샘플 없이도 동작. 텍스트 프롬프트 지원.",
        installPackages=["open_clip_torch", "torch"],
    ),
    # ── 시계열 분류
    "moment_large": BackboneModel(
        id="moment_large",
        name="MOMENT-1-large",
        githubUrl="https://github.com/moment-timeseries-foundation-model/moment",
        paperUrl="https://arxiv.org/abs/2402.03885",
        downloadUrl="https://huggingface.co/AutonLab/MOMENT-1-large/resolve/main/pytorch_model.bin",
        framework="pytorch",
        description="시계열 파운데이션 모델. 분류·이상탐지·예측 공식 지원. few-shot 가능.",
        installPackages=["momentfm", "torch"],
    ),
    "itransformer": BackboneModel(
        id="itransformer",
        name="iTransformer",
        githubUrl="https://github.com/thuml/iTransformer",
        paperUrl="https://arxiv.org/abs/2310.06625",
        downloadUrl="https://github.com/thuml/iTransformer",
        downloadNote="사전학습 체크포인트 없음 — 데이터셋별 학습 필요. GitHub에서 코드 클론.",
        framework="pytorch",
        description="ICLR 2024. 제조 멀티변수 시계열 분류·예측 강세. 변수 간 상관관계 학습.",
        installPackages=["torch"],
    ),
    "chronos2": BackboneModel(
        id="chronos2",
        name="Chronos-2",
        githubUrl="https://github.com/amazon-science/chronos-forecasting",
        paperUrl="https://arxiv.org/abs/2510.15821",
        downloadUrl="https://huggingface.co/amazon/chronos-2-small/resolve/main/pytorch_model.bin",
        framework="pytorch",
        description="2025.10 출시. T5 기반 파운데이션. 멀티변량+공변량 지원. fev-bench SOTA.",
        installPackages=["chronos-forecasting", "torch"],
    ),
    # ── 시계열 이상탐지
    "timesnet": BackboneModel(
        id="timesnet",
        name="TimesNet",
        githubUrl="https://github.com/thuml/Time-Series-Library",
        paperUrl="https://arxiv.org/abs/2210.02186",
        downloadUrl="https://github.com/thuml/Time-Series-Library",
        downloadNote="사전학습 체크포인트 없음 — 데이터셋별 학습 필요. THUML Time-Series-Library에서 코드 클론.",
        framework="pytorch",
        description="ICLR 2023. 주기성 기반 2D 변환. 분류·이상탐지·예측·보간 통합 지원. THUML 공식 라이브러리.",
        installPackages=["torch"],
    ),
    "ofa_gpt4ts": BackboneModel(
        id="ofa_gpt4ts",
        name="OFA (GPT4TS)",
        githubUrl="https://github.com/DAMO-DI-ML/NeurIPS2023-One-Fits-All",
        paperUrl="https://arxiv.org/abs/2310.00003",
        downloadUrl="https://huggingface.co/openai-community/gpt2/resolve/main/pytorch_model.bin",
        framework="pytorch",
        description="NeurIPS 2023. GPT-2 백본 파인튜닝으로 시계열 이상탐지·분류·예측 통합. 공개된 GPT-2 가중치 사용.",
        installPackages=["transformers", "torch"],
    ),
    # ── 시계열 예측
    "timesfm_25": BackboneModel(
        id="timesfm_25",
        name="TimesFM 2.5",
        githubUrl="https://github.com/google-research/timesfm",
        paperUrl="https://arxiv.org/abs/2310.10688",
        downloadUrl="https://huggingface.co/google/timesfm-2.5-200m-pytorch/resolve/main/pytorch_model.bin",
        framework="pytorch",
        description="200M 파라미터. 16k 컨텍스트. LoRA 파인튜닝 지원. Google Research.",
        installPackages=["timesfm", "torch", "peft"],
    ),
    "moirai2": BackboneModel(
        id="moirai2",
        name="Moirai 2.0",
        githubUrl="https://github.com/SalesforceAIResearch/uni2ts",
        paperUrl="https://arxiv.org/abs/2402.02592",
        downloadUrl="https://huggingface.co/Salesforce/moirai-2.0-R-large/resolve/main/pytorch_model.bin",
        framework="pytorch",
        description="확률적 예측. 불확실성 정량화 강점. Salesforce AI.",
        installPackages=["uni2ts", "torch"],
    ),
    # ── 표 분류/회귀
    "tabpfn3": BackboneModel(
        id="tabpfn3",
        name="TabPFN-3",
        githubUrl="https://github.com/PriorLabs/TabPFN",
        paperUrl="https://arxiv.org/abs/2605.13986",
        downloadUrl="https://huggingface.co/Prior-Labs/tabpfn_3/resolve/main/pytorch_model.bin",
        framework="pytorch",
        description="2026 TabArena SOTA. 단일 forward pass. 튜닝 불필요. 최대 1M 행 지원.",
        installPackages=["tabpfn"],
    ),
    "xgboost": BackboneModel(
        id="xgboost",
        name="XGBoost",
        githubUrl="https://github.com/dmlc/xgboost",
        downloadUrl="https://github.com/dmlc/xgboost",
        downloadNote="pip install xgboost 으로 설치. 별도 체크포인트 없음.",
        framework="other",
        description="대용량(>100k 행) 데이터 최강 베이스라인. 해석 용이. 빠른 학습.",
        installPackages=["xgboost", "scikit-learn"],
    ),
    "lightgbm": BackboneModel(
        id="lightgbm",
        name="LightGBM",
        githubUrl="https://github.com/microsoft/LightGBM",
        downloadUrl="https://github.com/microsoft/LightGBM",
        downloadNote="pip install lightgbm 으로 설치. 별도 체크포인트 없음.",
        framework="other",
        description="빠른 학습. 범주형 특성 자동 처리. 메모리 효율적.",
        installPackages=["lightgbm", "scikit-learn"],
    ),
    "catboost": BackboneModel(
        id="catboost",
        name="CatBoost",
        githubUrl="https://github.com/catboost/catboost",
        downloadUrl="https://github.com/catboost/catboost",
        downloadNote="pip install catboost 으로 설치. 별도 체크포인트 없음.",
        framework="other",
        description="범주형 특성이 많은 제조 데이터에 최적. 전처리 최소화.",
        installPackages=["catboost", "scikit-learn"],
    ),
    # ── 표 이상탐지
    "ecod": BackboneModel(
        id="ecod",
        name="ECOD (Empirical CDF)",
        githubUrl="https://github.com/yzhao062/pyod",
        paperUrl="https://arxiv.org/abs/2201.00382",
        downloadUrl="https://github.com/yzhao062/pyod",
        downloadNote="pip install pyod 으로 설치. 비모수적 방법, 별도 체크포인트 없음.",
        framework="other",
        description="IEEE TKDE 2023. 경험적 CDF 기반 비모수 이상탐지. 빠르고 해석 가능. 튜닝 불필요.",
        installPackages=["pyod", "scikit-learn"],
    ),
    "copod": BackboneModel(
        id="copod",
        name="COPOD (Copula-based)",
        githubUrl="https://github.com/yzhao062/pyod",
        paperUrl="https://arxiv.org/abs/2009.09463",
        downloadUrl="https://github.com/yzhao062/pyod",
        downloadNote="pip install pyod 으로 설치. 비모수적 방법, 별도 체크포인트 없음.",
        framework="other",
        description="ICDM 2020. 코풀라 기반 통계적 이상탐지. 매우 빠름. 고차원 데이터에서도 효과적.",
        installPackages=["pyod", "scikit-learn"],
    ),
    "deep_isolation_forest": BackboneModel(
        id="deep_isolation_forest",
        name="DeepIsolationForest",
        githubUrl="https://github.com/xuhongzuo/DeepOD",
        paperUrl="https://arxiv.org/abs/2206.06602",
        downloadUrl="https://github.com/xuhongzuo/DeepOD",
        downloadNote="pip install deepod 으로 설치. 별도 체크포인트 없음.",
        framework="pytorch",
        description="안정적 비지도 이상탐지. DeepOD 라이브러리로 간편 사용 가능.",
        installPackages=["deepod", "torch"],
    ),
}


BACKBONE_MODEL_MAP: dict[str, list[BackboneModel]] = {
    # ── 이미지 분류: 3개 (모두 실제 학습)
    "image__classification": [MODELS["swin_v2_b"], MODELS["convnext_v2_b"], MODELS["efficientnet_v2_m"]],
    # ── 나머지 이미지: 1개 (각 태스크 전용 트레이너)
    "image__segmentation": [MODELS["segformer_b5"]],
    "image__detection": [MODELS["yolo26n"]],
    "image__anomaly_detection": [MODELS["patchcore"]],
    "image__forecasting": [],
    "image__regression": [],
    # ── 시계열: 1개 (sklearn 기반 트레이너)
    "timeseries__classification": [MODELS["itransformer"]],
    "timeseries__anomaly_detection": [MODELS["timesnet"]],
    "timeseries__forecasting": [MODELS["chronos2"]],
    "timeseries__segmentation": [],
    "timeseries__detection": [],
    "timeseries__regression": [],
    # ── JSON/표: 1개 (sklearn 기반 트레이너)
    "json__classification": [MODELS["xgboost"]],
    "json__regression": [MODELS["xgboost"]],
    "json__anomaly_detection": [MODELS["ecod"]],
    "json__segmentation": [],
    "json__detection": [],
    "json__forecasting": [],
}


def get_recommended_models(data_type: DataType, task_type: TaskType) -> list[BackboneModel]:
    return BACKBONE_MODEL_MAP.get(f"{data_type}__{task_type}", [])


def get_model_by_id(model_id: str) -> BackboneModel | None:
    return MODELS.get(model_id)
